import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavMenu from './components/NavMenu'
import { getServerSession } from 'next-auth'

import SessionProvider from "@/app/components/SessionProvider"
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session} >
          <main>
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          >
          <Toaster 
            position="bottom-right"
            reverseOrder={true}
          />
          <NavMenu />
          {children}
          </ThemeProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
